
package com.aisino.ws.op;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-09-14T23:32:12.889+08:00
 * Generated source version: 2.7.18
 * 
 */
public final class IEInvWebServicePortType_IEInvWebServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.aisino.com", "IEInvWebService");

    private IEInvWebServicePortType_IEInvWebServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IEInvWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IEInvWebService ss = new IEInvWebService(wsdlURL, SERVICE_NAME);
        IEInvWebServicePortType port = ss.getIEInvWebServiceHttpPort();  
        
        {
        System.out.println("Invoking kxzpycxInterface...");
        java.lang.String _kxzpycxInterface_in0 = "_kxzpycxInterface_in0-331005098";
        java.lang.String _kxzpycxInterface__return = port.kxzpycxInterface(_kxzpycxInterface_in0);
        System.out.println("kxzpycxInterface.result=" + _kxzpycxInterface__return);


        }
        {
        System.out.println("Invoking fpkccxInterface...");
        java.lang.String _fpkccxInterface_in0 = "_fpkccxInterface_in044690244";
        java.lang.String _fpkccxInterface__return = port.fpkccxInterface(_fpkccxInterface_in0);
        System.out.println("fpkccxInterface.result=" + _fpkccxInterface__return);


        }
        {
        System.out.println("Invoking yhzxxcxInterface...");
        java.lang.String _yhzxxcxInterface_in0 = "_yhzxxcxInterface_in0-1025258167";
        java.lang.String _yhzxxcxInterface__return = port.yhzxxcxInterface(_yhzxxcxInterface_in0);
        System.out.println("yhzxxcxInterface.result=" + _yhzxxcxInterface__return);


        }
        {
        System.out.println("Invoking eiInterface...");
        java.lang.String _eiInterface_in0 = "_eiInterface_in0-1588734716";
        java.lang.String _eiInterface__return = port.eiInterface(_eiInterface_in0);
        System.out.println("eiInterface.result=" + _eiInterface__return);


        }
        {
        System.out.println("Invoking fpkjInterface...");
        java.lang.String _fpkjInterface_in0 = "_fpkjInterface_in0-694623840";
        java.lang.String _fpkjInterface__return = port.fpkjInterface(_fpkjInterface_in0);
        System.out.println("fpkjInterface.result=" + _fpkjInterface__return);


        }
        {
        System.out.println("Invoking kcmxcxInterface...");
        java.lang.String _kcmxcxInterface_in0 = "_kcmxcxInterface_in02128575630";
        java.lang.String _kcmxcxInterface__return = port.kcmxcxInterface(_kcmxcxInterface_in0);
        System.out.println("kcmxcxInterface.result=" + _kcmxcxInterface__return);


        }
        {
        System.out.println("Invoking djxxcxInterface...");
        java.lang.String _djxxcxInterface__return = port.djxxcxInterface();
        System.out.println("djxxcxInterface.result=" + _djxxcxInterface__return);


        }
        {
        System.out.println("Invoking jspxxcxInterface...");
        java.lang.String _jspxxcxInterface_in0 = "_jspxxcxInterface_in0-432671345";
        java.lang.String _jspxxcxInterface__return = port.jspxxcxInterface(_jspxxcxInterface_in0);
        System.out.println("jspxxcxInterface.result=" + _jspxxcxInterface__return);


        }
        {
        System.out.println("Invoking fpcyInterface...");
        java.lang.String _fpcyInterface_in0 = "_fpcyInterface_in0262594021";
        java.lang.String _fpcyInterface__return = port.fpcyInterface(_fpcyInterface_in0);
        System.out.println("fpcyInterface.result=" + _fpcyInterface__return);


        }

        System.exit(0);
    }

}
