
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.aisino.ws.op;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-09-14T23:32:12.948+08:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "IEInvWebService",
                      portName = "IEInvWebServiceHttpPort",
                      targetNamespace = "http://ws.aisino.com",
                      wsdlLocation = "file:/D:/work/eclipse.work.invoice/efs-e-invoice-sell/e-invoice-pro/src/main/java/hangxin/invoice/bean/op.wsdl",
                      endpointInterface = "com.aisino.ws.op.IEInvWebServicePortType")
                      
public class IEInvWebServicePortTypeImpl implements IEInvWebServicePortType {

    private static final Logger LOG = Logger.getLogger(IEInvWebServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.aisino.ws.op.IEInvWebServicePortType#kxzpycxInterface(java.lang.String  in0 )*
     */
    public java.lang.String kxzpycxInterface(java.lang.String in0) { 
        LOG.info("Executing operation kxzpycxInterface");
        System.out.println(in0);
        try {
            java.lang.String _return = "_return745692632";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.aisino.ws.op.IEInvWebServicePortType#fpkccxInterface(java.lang.String  in0 )*
     */
    public java.lang.String fpkccxInterface(java.lang.String in0) { 
        LOG.info("Executing operation fpkccxInterface");
        System.out.println(in0);
        try {
            java.lang.String _return = "_return-1662455580";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.aisino.ws.op.IEInvWebServicePortType#yhzxxcxInterface(java.lang.String  in0 )*
     */
    public java.lang.String yhzxxcxInterface(java.lang.String in0) { 
        LOG.info("Executing operation yhzxxcxInterface");
        System.out.println(in0);
        try {
            java.lang.String _return = "_return1301095472";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.aisino.ws.op.IEInvWebServicePortType#eiInterface(java.lang.String  in0 )*
     */
    public java.lang.String eiInterface(java.lang.String in0) { 
        LOG.info("Executing operation eiInterface");
        System.out.println(in0);
        try {
            java.lang.String _return = "_return-478027762";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.aisino.ws.op.IEInvWebServicePortType#fpkjInterface(java.lang.String  in0 )*
     */
    public java.lang.String fpkjInterface(java.lang.String in0) { 
        LOG.info("Executing operation fpkjInterface");
        System.out.println(in0);
        try {
            java.lang.String _return = "_return1097826552";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.aisino.ws.op.IEInvWebServicePortType#kcmxcxInterface(java.lang.String  in0 )*
     */
    public java.lang.String kcmxcxInterface(java.lang.String in0) { 
        LOG.info("Executing operation kcmxcxInterface");
        System.out.println(in0);
        try {
            java.lang.String _return = "_return-45771384";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.aisino.ws.op.IEInvWebServicePortType#djxxcxInterface(*
     */
    public java.lang.String djxxcxInterface() { 
        LOG.info("Executing operation djxxcxInterface");
        try {
            java.lang.String _return = "_return954076628";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.aisino.ws.op.IEInvWebServicePortType#jspxxcxInterface(java.lang.String  in0 )*
     */
    public java.lang.String jspxxcxInterface(java.lang.String in0) { 
        LOG.info("Executing operation jspxxcxInterface");
        System.out.println(in0);
        try {
            java.lang.String _return = "_return2071432247";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.aisino.ws.op.IEInvWebServicePortType#fpcyInterface(java.lang.String  in0 )*
     */
    public java.lang.String fpcyInterface(java.lang.String in0) { 
        LOG.info("Executing operation fpcyInterface");
        System.out.println(in0);
        try {
            java.lang.String _return = "_return-976458519";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
