package com.aisino.ws.op;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-09-14T23:32:12.970+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://ws.aisino.com", name = "IEInvWebServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface IEInvWebServicePortType {

    @WebResult(name = "out", targetNamespace = "http://ws.aisino.com")
    @RequestWrapper(localName = "kxzpycxInterface", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.op.KxzpycxInterface")
    @WebMethod
    @ResponseWrapper(localName = "kxzpycxInterfaceResponse", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.op.KxzpycxInterfaceResponse")
    public java.lang.String kxzpycxInterface(
        @WebParam(name = "in0", targetNamespace = "http://ws.aisino.com")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://ws.aisino.com")
    @RequestWrapper(localName = "fpkccxInterface", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.op.FpkccxInterface")
    @WebMethod
    @ResponseWrapper(localName = "fpkccxInterfaceResponse", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.op.FpkccxInterfaceResponse")
    public java.lang.String fpkccxInterface(
        @WebParam(name = "in0", targetNamespace = "http://ws.aisino.com")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://ws.aisino.com")
    @RequestWrapper(localName = "yhzxxcxInterface", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.op.YhzxxcxInterface")
    @WebMethod
    @ResponseWrapper(localName = "yhzxxcxInterfaceResponse", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.op.YhzxxcxInterfaceResponse")
    public java.lang.String yhzxxcxInterface(
        @WebParam(name = "in0", targetNamespace = "http://ws.aisino.com")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://ws.aisino.com")
    @RequestWrapper(localName = "eiInterface", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.op.EiInterface")
    @WebMethod
    @ResponseWrapper(localName = "eiInterfaceResponse", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.op.EiInterfaceResponse")
    public java.lang.String eiInterface(
        @WebParam(name = "in0", targetNamespace = "http://ws.aisino.com")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://ws.aisino.com")
    @RequestWrapper(localName = "fpkjInterface", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.op.FpkjInterface")
    @WebMethod
    @ResponseWrapper(localName = "fpkjInterfaceResponse", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.op.FpkjInterfaceResponse")
    public java.lang.String fpkjInterface(
        @WebParam(name = "in0", targetNamespace = "http://ws.aisino.com")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://ws.aisino.com")
    @RequestWrapper(localName = "kcmxcxInterface", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.op.KcmxcxInterface")
    @WebMethod
    @ResponseWrapper(localName = "kcmxcxInterfaceResponse", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.op.KcmxcxInterfaceResponse")
    public java.lang.String kcmxcxInterface(
        @WebParam(name = "in0", targetNamespace = "http://ws.aisino.com")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://ws.aisino.com")
    @RequestWrapper(localName = "djxxcxInterface", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.op.DjxxcxInterface")
    @WebMethod
    @ResponseWrapper(localName = "djxxcxInterfaceResponse", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.op.DjxxcxInterfaceResponse")
    public java.lang.String djxxcxInterface();

    @WebResult(name = "out", targetNamespace = "http://ws.aisino.com")
    @RequestWrapper(localName = "jspxxcxInterface", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.op.JspxxcxInterface")
    @WebMethod
    @ResponseWrapper(localName = "jspxxcxInterfaceResponse", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.op.JspxxcxInterfaceResponse")
    public java.lang.String jspxxcxInterface(
        @WebParam(name = "in0", targetNamespace = "http://ws.aisino.com")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://ws.aisino.com")
    @RequestWrapper(localName = "fpcyInterface", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.op.FpcyInterface")
    @WebMethod
    @ResponseWrapper(localName = "fpcyInterfaceResponse", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.op.FpcyInterfaceResponse")
    public java.lang.String fpcyInterface(
        @WebParam(name = "in0", targetNamespace = "http://ws.aisino.com")
        java.lang.String in0
    );
}
