package com.aisino.ws.qz;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-09-14T23:25:28.881+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://ws.aisino.com", name = "IEInvWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface IEInvWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "eiInterface", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.qz.EiInterface")
    @WebMethod
    @ResponseWrapper(localName = "eiInterfaceResponse", targetNamespace = "http://ws.aisino.com", className = "com.aisino.ws.qz.EiInterfaceResponse")
    public java.lang.String eiInterface(
        @WebParam(name = "requestDownLoadXML", targetNamespace = "http://ws.aisino.com")
        java.lang.String requestDownLoadXML
    );
}
