
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.aisino.ws.qz;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-09-14T23:25:28.866+08:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "IEInvWebService",
                      portName = "IEInvWebServicePort",
                      targetNamespace = "http://ws.aisino.com",
                      wsdlLocation = "file:/D:/work/eclipse.work.invoice/efs-e-invoice-sell/e-invoice-pro/src/main/java/hangxin/invoice/bean/qz.wsdl",
                      endpointInterface = "com.aisino.ws.qz.IEInvWebService")
                      
public class IEInvWebServiceImpl implements IEInvWebService {

    private static final Logger LOG = Logger.getLogger(IEInvWebServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.aisino.ws.qz.IEInvWebService#eiInterface(java.lang.String  requestDownLoadXML )*
     */
    public java.lang.String eiInterface(java.lang.String requestDownLoadXML) { 
        LOG.info("Executing operation eiInterface");
        System.out.println(requestDownLoadXML);
        try {
            java.lang.String _return = "_return-1506448109";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
