
package com.aisino.ws.qz;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-09-14T23:25:28.808+08:00
 * Generated source version: 2.7.18
 * 
 */
public final class IEInvWebService_IEInvWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.aisino.com", "IEInvWebService");

    private IEInvWebService_IEInvWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IEInvWebService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IEInvWebService_Service ss = new IEInvWebService_Service(wsdlURL, SERVICE_NAME);
        IEInvWebService port = ss.getIEInvWebServicePort();  
        
        {
        System.out.println("Invoking eiInterface...");
        java.lang.String _eiInterface_requestDownLoadXML = "_eiInterface_requestDownLoadXML1931106371";
        java.lang.String _eiInterface__return = port.eiInterface(_eiInterface_requestDownLoadXML);
        System.out.println("eiInterface.result=" + _eiInterface__return);


        }

        System.exit(0);
    }

}
