package com.htxx.service.scserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.13
 * 2017-05-15T17:36:25.478+08:00
 * Generated source version: 3.0.13
 * 
 */
@WebService(targetNamespace = "com.htxx.service", name = "WbServiceI")
@XmlSeeAlso({ObjectFactory.class})
public interface WbServiceI {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getData", targetNamespace = "com.htxx.service", className = "com.htxx.service.scserver.GetData")
    @WebMethod(action = "http://com.htxx.service/getData")
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "com.htxx.service", className = "com.htxx.service.scserver.GetDataResponse")
    public java.lang.String getData(
        @WebParam(name = "number", targetNamespace = "")
        java.lang.String number,
        @WebParam(name = "invoicecode", targetNamespace = "")
        java.lang.String invoicecode,
        @WebParam(name = "invoiceno", targetNamespace = "")
        java.lang.String invoiceno
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendData", targetNamespace = "com.htxx.service", className = "com.htxx.service.scserver.SendData")
    @WebMethod(action = "http://com.htxx.service/sendData")
    @ResponseWrapper(localName = "sendDataResponse", targetNamespace = "com.htxx.service", className = "com.htxx.service.scserver.SendDataResponse")
    public java.lang.String sendData(
        @WebParam(name = "data", targetNamespace = "")
        java.lang.String data
    );
}
