package com.efuture.portal.utils;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public interface Constant {
	final public static Map<String,String> WeixTokenMap = new HashMap<String, String>();
	final public static String WeixAppID = "wx27b56f443e18a9ab";
	final public static String WeixSecret = "4447f8e8dd7a15e40e5e6dd2b2da773a";
	
	public static final String VERIFYCODE = "verifycode";
	String NOTICE = "notice";
	String UTF8 = "UTF-8";
	static final String TAG_NAME = "tag_name";
	static final String NODE_VALUE = "node_value";
	static final String[] TAG_NAME_KEYS = new String[] { TAG_NAME };
	String SERIALNO = "serialno";
	int ONE = 1;
	int ONE_HUNDRERD = 100;
	int FIVE_HUNDRERD = 500;
	String DIGEST_REP = "digest_rep";
	String COMPANYID = "companyid";
	String QZJ_URL = "qzj_url";
	String LOTTERYEXRATE = "lotteryexrate";
	List<String> SECOND_LOTTERY = Arrays.asList(new String[] { "201" });
	String DAY = "day";
	String COMPANYNAME = "companyname";
	String[] COMPANYNAME_DAY_KEYS = new String[] { COMPANYNAME, DAY };
	String TOTAL = "total";
	String PAGESIZE = "pagesize";
	String PAGEINDEX = "pageindex";
	String POINT = "point";
	String CARDNO = "cardno";
	String DIRECTION = "direction";
	String LEVELID = "levelid";
	String MOBILE_VERIFY = "mobile_verify";
	String ERROR_OPENID = "error_openid";
	String ERROR_PARTNERID = "error_partnerid";
	String PARTNERID = "partnerid";
	String MERCHANT_USER = "merchant_user";
	String SELLERID = "sellerid";
	String SHEETID = "sheetid";
	String SELLERNAME = "sellername";
	String AMOUNT = "amount";
	String TABLENAME = "tablename";
	String NOTES = "notes";
	String COSTSOURCE = "costsource";
	String HEADID = "headid";
	String BILLSHEETID = "billsheetid";
	String DATASOURCETYPE = "datasourcetype";
	String EDITOR = "editor";
	String ITEMS = "items";
	String REFCOSTCODE = "refcostcode";
	String COSTCODE = "costcode";
	String REFSHEETID = "refsheetid";
	String ORDERTIME = "ordertime";
	String FLAG = "flag";
	String INSERT = "insert";
	String DEPTID = "deptid";
	String ORDERID = "orderid";
	String DETAILID = "detailid";
	String GOODSID = "goodsid";
	String SKUID = "skuid";
	String CHANNELORDERID = "channelorderid";
	String CHANNELDETAILID = "channeldetailid";
	public static final String PRIMARY_EXCEPTION = "Duplicate entry";
}
